apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "spring-music"
spec:
  replicas: 6
  minReadySeconds: 30
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: "25%"
  template:
    metadata:
      labels:
        app: "spring-music"
    spec:
      containers:
        - name: "spring-music"
          image: "harbor.pks.gcp.techman.cloud/library/spring-music"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "spring-music-lb"
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: "spring-music"
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer

