# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assemble
    - name: Push Docker Image to Harbor  
      uses: christian-korneck/update-container-description-action@v1
      with:
        # the destination container repo (i.e. my-user/my-repo or myserver.com/my-user/my-repo)
        destination_container_repo: demo/spring-music:latest
        # repo provider type (dockerhub, quay, harbor2)
        provider: https://harbor.techman.cloud
